### ISSUE TITLE
Bad include filename in example 

### ISSUE THREAD

**Issue by mgwerder** [TheNitek/CatGFX#1]
Just tried to run the example and figured out that catGFX.h no longer exists instead <catprinter.h> would be apropriate. Maybe this is worth correcting....

**Comment by TheNitek** [comment]
I think you might have mixed the example from master branch with the library from release 0.0.1.
On master the header file has been renamed to CatGFX.h to match the repo name which was a recommendation from the Arduino LIbrary Bot. Just didn't seem to be worth a new release.
