### ISSUE TITLE
Crash when attempting to connect to printer

### ISSUE THREAD

**Issue by dizeeee** [TheNitek/CatGFX#2]
When calling `cat.connect()` while the printer is on, my ESP32S3 crashes with the error message below. I have tried following the example code, with the only change being that I hardcode the BLEAddress so the board can actually find the printer.

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40376cfc
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x43c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2a3c
SHA-256 comparison failed:
Calculated: dcde8d8a4817d9bf5d5d69a7247667264e4e10ac7493514868b61f5aa6146539
Expected: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
Attempting to boot anyway...
entry 0x403c98d8
```

**Comment by TheNitek** [comment]
There was a similar problem with the older ESP32 frameworks, but I have not tried this lib yet on a S3. Can you maybe decode th exception (https://github.com/me-no-dev/EspExceptionDecoder)
